
text_casino_name = "Name of the casino. For example - PlayRize Casino"
text_casino_theme = "Theme of the casino. Pick from the dropdown or add a new one"
text_url_casino = "URL of the casino. For example - https://vavada.com"
text_url_casinoguru = "URL of this casino on Casinoguru. For example - https://casinoguru-en.com/vavada-casino-review"
text_url_general_tc = "URL of General T&C. For example - https://www.luckyblock.com/en/terms"
text_url_bonus_tc = "URL of Bonus T&C. For example - https://www.luckyblock.com/en/bonus-terms"
text_url_bonus_main_page = "URL of main bonus page. For example - https://www.luckyblock.com/en/promotions"
text_casino_owner = "Casino company name. For example Luckyblock casino is owned by Entretenimiento Rojo B.V."
text_casino_establish_year = "Year of establishment of the casino"
text_casino_website_languages = "List of languages present on the website"
text_casino_livechat_languages = "List of languages in livechat"
text_casino_blocked_countries = "List of restricted countries"
text_casino_license = "The license under which the casino operates"
text_casino_vpn = "If VPN usage is allowed, please check the box"
text_casino_sportsbook = "If the casino has a sportsbook, please check the box"
text_casino_bonus_hunt = "If bonus hunt is allowed, please check the box"
text_casino_tournaments = "If the casino has tournaments, please check the box"
text_casino_responsible_gambling_deposit_limit = "A predetermined maximum amount of money that a player can deposit into their gambling account within a specific timeframe (daily, weekly, or monthly)"
text_casino_responsible_gambling_wager_limit = "A predefined maximum amount of money that a player can wager (bet) within a specific period, typically daily, weekly, or monthly"
text_casino_responsible_gambling_loss_limit = "A set limit on the total losses a player can incur during a specific time frame (daily, weekly, or monthly)"
text_casino_responsible_gambling_session_limit = "A restriction on the amount of time a player can spend in a single gambling session"
text_casino_responsible_gambling_self_exclusion = "A voluntary agreement by a player to exclude themselves from accessing the gambling platform for a specific duration, often ranging from a few months to several years"
text_gamstop_self_exclusion = "GAMSTOP will prevent from using gambling websites and apps run by companies licensed in Great Britain, for a period of players choosing"
text_casino_responsible_gambling_cool_off = "A temporary suspension of a player's account, preventing them from accessing the gambling platform for a shorter period than self-exclusion"
text_casino_responsible_gambling_reality_check = "Periodic notifications or alerts sent to players during their gambling session, reminding them of the time spent playing and the amounts wagered"
text_casino_responsible_gambling_self_assessment = "Tools or questionnaires provided to players to assess their gambling behavior, habits, and potential risk of developing gambling-related problems"
text_casino_responsible_gambling_withdrawal_lock = "A feature that allows players to lock in their withdrawal requests, preventing them from canceling or reversing the withdrawal process"

# ---------------------- JS Casino ----------------------------------------------- #
text_casino_other_social_bonuses = "If the casino has social bonuses in Twitter, Telgram, etc., please check the box"
text_casino_withdrawal_limit = "Daily, weekly, and monthly withdrawal limits in EUR. If, for example, there are no weekly limits, please leave the field empty."
text_casino_min_wagering = "The minimum wagering or rollover requirement indicates the number of times a deposit must be played through (typically 1x-3x) before being eligible for withdrawal from the casino"
# ==================================================================================================================== #

text_bonus_type = "Type of the bonus. For example - Welcome bonus"
text_bonus_subtype = "Subtype of the bonus. For example - Christmas bonus."
text_bonus_name = "Name of the bonus. For example - 'Welcome Bonus Pack'"
text_bonus_url = "URL of the particular bonus. For example - https://vavada.com/welcome-bonus"
text_bonus_amount = "The maximum bonus amount that the casino can match. Usually defined defined as: 'up to 200 EUR'"
text_bonus_min_deposit = "Minimum deposit to active the bonus. Usually around 10 EUR"

text_bonus_promotion_period = "If there is something specific like Christmas bonus, then we should add the period during which it is available"
text_bonus_bonus_max_win = "Max win is the same as max withdrawal from the bonus."
text_bonus_wagering_bonus_deposit = "Applies if wagering requirements are for bonus + deposit"
text_bonus_wagering_bonus_only = "Applies if wagering requirements are for bonus only"
text_bonus_wagering_turnover_requirement = "For example - Wagering requirements of x30 apply for the bonus. The bonus is awarded in parts of 10% of the activated bonus amount, after wagering every 10% x30 on the bonus."
text_bonus_wagering_turnover_example = "For example - To activate the Welcome Bonus, a deposit of €100 is made. The total wagering amount is €100 x 30 = €3000, therefore, after every €300 wagered, €10 will be credited to the balance."

text_bonus_calculations_bonus_deposit = "Manually calculate the total bonus amount when wagering applies to both the bonus and deposit. For instance, if you deposited 100 EUR and received a 100 EUR bonus, the total bonus amount would be 200 EUR."
text_bonus_calculations_bonus_only = "Manually calculate the total bonus amount when wagering applies to bonus only. For instance, if you deposited 100 EUR and received a 100 EUR bonus, the total bonus amount would be 100 EUR."
text_bonus_calculations_bonus_freespins = "Manually calculate the total value of awarded free spins and add the bonus only amount. For example, if you get 50 free spins where each spin is 0.1 EUR then the total value is 5 EUR"
text_bonus_calculations_amount_bonus_deposit = "This calculation shows how many bets (using max bet for the bonus) is needed to wager the bonus. This applies to bonus + deposit wagering type. <br> FORMULA = BONUS + DEPOSIT (TOTAL BONUS AMOUNT) * BONUS + DEPOSIT (WAGERING) / AMOUNT (MAX BET)"
text_bonus_calculations_amount_bonus_only = "This calculation shows how many bets (using max bet for the bonus) is needed to wager the bonus. This applies to bonus only wagering type. <br> FORMULA = BONUS ONLY (TOTAL BONUS AMOUNT) * BONUS ONLY (WAGERING) / AMOUNT (MAX BET)"

# ---------------------- JS Bonuse ----------------------------------------------- #
text_bonus_value_percentage = "Bonus value in percentage. So, for example if it says '200% up to 200 EUR' then bonus value is 200%"
text_bonus_availability = "For example, if the bonus is only available on Tuesday, please select 'Tuesday' from the dropdown menu"
text_bonus_expiration = "This means that the player has X days to wager his bonus. Otherwise it will be canceled, etc."
text_bonus_game_restriction = "Pick slots that you can't play with active bonus"
text_bonus_rtp_restriction = "Some slots are not allowed for bonus wagering due to high RTP"
text_bonus_country_restriction = "Pick countries that can't receive this bonus"
text_bonus_free_spins_amount = "Number of free spins that you can get by activating this bonus"
text_bonus_free_spins_one_spin_value = "The value of one free spin. Usually around 0.1 EUR"
text_bonus_free_spins_slot_availability = "Slots where you can use free spins"
text_bonus_free_spins_wager = "Wagering amount for free spins"
text_bonus_turnover = "If the bonus is of the turnover type, please tick the box"
text_bonus_wagering_contribution = "Usually slots are 100% and everything else (roulette, blackjack, etc) is 0% or 5%"
text_bonus_max_bet = "Maximum bet allowed by T&C"
text_bonus_max_bet_automatic = "In some casinos max bet is restricted automatically meaning that you can't place a bigger bet than allowed if you have an active bonus. However, in some casinos this is not automatically restricted and customer can easily make a mistake by placing a higher bet and thus canceling his bonus and winnings from it."
text_bonus_other_bonus_buy = "For example - Can I buy 'Buy Feature' in Money Train 3 with an active welcome bonus? My winnings won't be canceled?"
text_bonus_other_special_notes = "Something worth mentioning. For example - Bonus is available only via Skrill deposit"
# ==================================================================================================================== #
