
text_casino_name = "Name of the casino. For example - PlayRize Casino"
text_url_casino = "URL of the casino. For example - https://vavada.com"
text_url_casinoguru = "URL of this casino on Casinoguru. For example - https://casinoguru-en.com/vavada-casino-review"
text_url_general_tc = "URL of General T&C. For example - https://www.luckyblock.com/en/terms"
text_url_bonus_tc = "URL of Bonus T&C. For example - https://www.luckyblock.com/en/bonus-terms"
text_url_bonus_main_page = "URL of main bonus page. For example - https://www.luckyblock.com/en/promotions"
text_casino_owner = "Casino company name. For example Luckyblock casino is owned by Entretenimiento Rojo B.V."
text_casino_establish_year = "Year of establishment of the casino"
text_casino_website_languages = "List of languages present on the website"
text_casino_livechat_languages = "List of languages in livechat"
text_casino_blocked_countries = "List of restricted countries"
text_casino_license = "The license under which the casino operates"
text_casino_vpn = "If VPN usage is allowed, please check the box"
text_casino_sportsbook = "If the casino has a sportsbook, please check the box"
text_casino_bonus_hunt = "If bonus hunt is allowed, please check the box"
