# Generated by Django 5.0 on 2023-12-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cryptocurrency',
            options={'ordering': ['id'], 'verbose_name': 'Crypto Currency', 'verbose_name_plural': 'Crypto Currencies'},
        ),
        migrations.AlterField(
            model_name='licensingauthority',
            name='validator_url',
            field=models.URLField(blank=True, null=True, verbose_name='Validator Url'),
        ),
    ]
