# Generated by Django 5.0 on 2023-12-22 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mindep',
            name='symbol_classic',
        ),
        migrations.RemoveField(
            model_name='mindep',
            name='symbol_crypto',
        ),
        migrations.AddField(
            model_name='mindep',
            name='symbol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='min_dip_symbol', to='app_casinos.basecurrency'),
        ),
    ]
