# Generated by Django 5.0 on 2024-01-02 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonus',
            name='bonus_subtypes',
        ),
        migrations.DeleteModel(
            name='BonusSubtype',
        ),
    ]
