# Generated by Django 5.0 on 2023-12-24 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdata',
            name='signature',
            field=models.CharField(choices=[('not_signed', 'Not Signed'), ('signed', 'Signed')], default=None, max_length=20),
        ),
    ]
