# Generated by Django 5.0 on 2023-12-22 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0002_remove_mindep_symbol_classic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mindep',
            name='min_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mindep',
            name='selected_source',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('terms_and_conditions', 'Terms & Conditions'), ('support', 'Support'), ('website', 'Website')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='mindep',
            name='symbol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='min_dip_symbol', to='app_casinos.basecurrency'),
        ),
    ]
