# Generated by Django 5.0 on 2023-12-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0002_alter_cryptocurrency_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licensingauthority',
            options={'ordering': ['id'], 'verbose_name': 'Licensing Authority', 'verbose_name_plural': 'Licensing Authorities'},
        ),
        migrations.AddField(
            model_name='casino',
            name='tournaments',
            field=models.BooleanField(default=False, verbose_name='Tournaments'),
        ),
    ]
