# Generated by Django 5.0 on 2023-12-24 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0002_alter_accountdata_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdata',
            name='signature',
            field=models.CharField(choices=[('not_signed', 'Not Signed'), ('signed', 'Signed')], max_length=20),
        ),
    ]
