# Generated by Django 5.0 on 2024-01-03 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0002_remove_bonus_bonus_subtypes_delete_bonussubtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='calculation_bonus_deposit',
            field=models.IntegerField(null=True, verbose_name='Amount of Bets Calculation (Bonus+Deposit)'),
        ),
        migrations.AddField(
            model_name='bonus',
            name='calculation_bonus_only',
            field=models.IntegerField(null=True, verbose_name='Amount of Bets Calculation (Bonus Only)'),
        ),
        migrations.AlterField(
            model_name='bonusslot',
            name='bonus',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonus_slot', to='app_casinos.bonus', to_field='slug'),
        ),
        migrations.AlterField(
            model_name='wagering',
            name='bonus',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wagering', to='app_casinos.bonus', to_field='slug'),
        ),
        migrations.CreateModel(
            name='WageringBonusPlusDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_plus_deposit', models.IntegerField(null=True, verbose_name='(Wagering) Bonus + Deposit')),
                ('bonus_only', models.IntegerField(null=True, verbose_name='(Wagering) Bonus Only')),
                ('selected_source', models.CharField(choices=[('undefined', 'Undefined'), ('terms_and_conditions', 'Terms & Conditions'), ('support', 'Support'), ('website', 'Website')], default='', max_length=20)),
                ('bonus', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wagering_bonus_plus_deposit', to='app_casinos.bonus', to_field='slug')),
            ],
        ),
    ]
