# Generated by Django 5.0 on 2023-12-18 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0003_alter_licensingauthority_options_casino_tournaments'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.CharField(max_length=255, verbose_name='Login')),
                ('password', models.IntegerField(blank=True, null=True)),
                ('casino', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_data', to='app_casinos.casino', to_field='slug')),
            ],
            options={
                'verbose_name': 'Account Data',
                'verbose_name_plural': 'Account Data',
                'ordering': ['id'],
            },
        ),
    ]
