# Generated by Django 5.0 on 2023-12-23 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0003_alter_mindep_min_value_alter_mindep_selected_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdata',
            name='password',
            field=models.CharField(max_length=15, verbose_name='Password'),
        ),
    ]
