# Generated by Django 5.0 on 2024-01-04 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0003_bonus_calculation_bonus_deposit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affiliatesprogram',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='casino',
            name='affiliate_program',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='link_affiliate',
        ),
        migrations.RemoveField(
            model_name='casino',
            name='link_affiliate_program',
        ),
        migrations.CreateModel(
            name='Affiliate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_affiliate_program', models.URLField(blank=True, null=True, verbose_name='affiliate Program URL')),
                ('link_affiliate', models.URLField(blank=True, null=True, verbose_name='Affiliate Link')),
                ('affiliate_program', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casino_affiliate_program', to='app_casinos.affiliatesprogram')),
                ('casino', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate', to='app_casinos.casino', to_field='slug')),
            ],
            options={
                'ordering': ['affiliate_program'],
            },
        ),
    ]
