# Generated by Django 5.0 on 2023-12-24 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0003_alter_accountdata_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountdata',
            name='signature',
        ),
    ]
