# Generated by Django 5.0 on 2023-12-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0004_accountdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casino',
            name='live_chat_competence',
            field=models.IntegerField(choices=[(1, 'High Competence'), (2, 'Above Average'), (3, 'Average'), (4, 'Below Average'), (5, 'Incompetent')], default='High Competence', max_length=20),
        ),
    ]
