# Generated by Django 5.0 on 2024-01-04 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0004_alter_affiliatesprogram_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wageringbonusplusdeposit',
            name='bonus_only',
            field=models.IntegerField(blank=True, null=True, verbose_name='(Wagering) Bonus Only'),
        ),
        migrations.AlterField(
            model_name='wageringbonusplusdeposit',
            name='bonus_plus_deposit',
            field=models.IntegerField(blank=True, null=True, verbose_name='(Wagering) Bonus + Deposit'),
        ),
    ]
