# Generated by Django 5.0 on 2023-12-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0004_remove_accountdata_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecurrency',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Name Currency'),
        ),
        migrations.AlterField(
            model_name='basecurrency',
            name='symbol',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Symbol Currency'),
        ),
    ]
