# Generated by Django 5.0 on 2023-12-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0005_alter_basecurrency_name_alter_basecurrency_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casino',
            name='classic_currency',
            field=models.ManyToManyField(related_name='casino_classic_currency', to='app_casinos.classiccurrency'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='crypto_currencies',
            field=models.ManyToManyField(related_name='casino_crypto_currencies', to='app_casinos.cryptocurrency'),
        ),
    ]
