# Generated by Django 5.0 on 2023-12-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0005_alter_casino_live_chat_competence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casino',
            name='live_chat_competence',
            field=models.IntegerField(choices=[(1, 'High Competence'), (2, 'Above Average'), (3, 'Average'), (4, 'Below Average'), (5, 'Incompetent')], default='High Competence'),
        ),
    ]
