# Generated by Django 5.0 on 2024-01-04 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0005_alter_wageringbonusplusdeposit_bonus_only_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='bonus_only',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bonus Only'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='bonus_plus_deposit',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bonus + Deposit'),
        ),
    ]
