# Generated by Django 5.0 on 2024-01-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0006_alter_bonus_bonus_only_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='calculation_bonus_deposit',
            field=models.IntegerField(blank=True, null=True, verbose_name='Amount of Bets Calculation (Bonus+Deposit)'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='calculation_bonus_only',
            field=models.IntegerField(blank=True, null=True, verbose_name='Amount of Bets Calculation (Bonus Only)'),
        ),
    ]
