# Generated by Django 5.0 on 2023-12-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0006_alter_casino_live_chat_competence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdata',
            name='log',
            field=models.CharField(max_length=50, verbose_name='Login'),
        ),
        migrations.AlterField(
            model_name='accountdata',
            name='password',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Password'),
        ),
    ]
