# Generated by Django 5.0 on 2023-12-23 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0006_alter_accountdata_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdata',
            name='log',
            field=models.CharField(max_length=50, unique=True, verbose_name='Login'),
        ),
    ]
