# Generated by Django 5.0 on 2024-01-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0007_alter_bonus_calculation_bonus_deposit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='calculation_bonus_deposit',
            field=models.FloatField(blank=True, null=True, verbose_name='Amount of Bets Calculation (Bonus+Deposit)'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='calculation_bonus_only',
            field=models.FloatField(blank=True, null=True, verbose_name='Amount of Bets Calculation (Bonus Only)'),
        ),
    ]
