# Generated by Django 5.0 on 2023-12-30 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0007_alter_bonus_link_alter_bonus_name_alter_bonus_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusSubtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255, verbose_name='Name Bonus Subtype')),
            ],
        ),
        migrations.CreateModel(
            name='BonusType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255, verbose_name='Name Bonus Type')),
            ],
        ),
        migrations.RemoveField(
            model_name='bonus',
            name='description',
        ),
        migrations.AddField(
            model_name='bonus',
            name='bonus_subtypes',
            field=models.ManyToManyField(related_name='bonus', to='app_casinos.bonussubtype'),
        ),
        migrations.AddField(
            model_name='bonus',
            name='bonus_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonus', to='app_casinos.bonustype'),
        ),
    ]
