# Generated by Django 5.0 on 2023-12-23 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0008_alter_accountdata_casino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdata',
            name='casino',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_data', to='app_casinos.casino', to_field='slug'),
        ),
    ]
