# Generated by Django 5.0 on 2024-01-05 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0008_alter_bonus_calculation_bonus_deposit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonusslot',
            name='game',
            field=models.ManyToManyField(blank=True, related_name='bonus_game', to='app_casinos.game'),
        ),
        migrations.AlterField(
            model_name='freespinamount',
            name='bonus',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='free_spin_amount', to='app_casinos.bonus', to_field='slug'),
        ),
        migrations.AlterField(
            model_name='freespinamount',
            name='value',
            field=models.IntegerField(blank=True, null=True, verbose_name='Free Spins value'),
        ),
        migrations.AlterField(
            model_name='onespin',
            name='bonus',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='one_spin', to='app_casinos.bonus', to_field='slug'),
        ),
        migrations.AlterField(
            model_name='onespin',
            name='value',
            field=models.FloatField(blank=True, null=True, verbose_name='One Spin value'),
        ),
        migrations.AlterField(
            model_name='wager',
            name='bonus',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wager', to='app_casinos.bonus', to_field='slug'),
        ),
        migrations.AlterField(
            model_name='wager',
            name='value',
            field=models.IntegerField(blank=True, null=True, verbose_name='Wager value'),
        ),
    ]
