# Generated by Django 5.0 on 2023-12-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0008_alter_cryptocurrency_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casino',
            name='established',
            field=models.PositiveIntegerField(blank=True, help_text='Year of establishment of the casino', null=True, verbose_name='Year of Establishment'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='owner',
            field=models.CharField(blank=True, help_text='Casino company name. For example Luckyblock casino is owned by Entretenimiento Rojo B.V.', max_length=255, null=True, verbose_name='Casino Owner'),
        ),
    ]
