# Generated by Django 5.0 on 2024-01-05 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0009_alter_bonusslot_game_alter_freespinamount_bonus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affiliate',
            name='casino',
        ),
        migrations.AddField(
            model_name='casino',
            name='affiliate',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casino', to='app_casinos.affiliate'),
        ),
    ]
