# Generated by Django 5.0 on 2023-12-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0009_alter_casino_established_alter_casino_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='name2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Country name2'),
        ),
    ]
