# Generated by Django 5.0 on 2023-12-31 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0009_alter_bonus_bonus_subtypes_alter_bonus_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='bonus_subtypes',
            field=models.ManyToManyField(blank=True, related_name='bonus', to='app_casinos.bonussubtype'),
        ),
    ]
