# Generated by Django 5.0 on 2023-12-31 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0010_alter_bonus_bonus_subtypes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonustype',
            options={'ordering': ['id'], 'verbose_name': 'Bonus Type', 'verbose_name_plural': 'Types of Bonuses'},
        ),
    ]
