# Generated by Django 5.0 on 2023-12-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0011_alter_country_options_alter_country_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdata',
            name='password',
            field=models.CharField(default='', max_length=15, verbose_name='Password'),
        ),
    ]
