# Generated by Django 5.0 on 2023-12-23 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0011_alter_accountdata_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdata',
            name='log',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Login'),
        ),
        migrations.AlterField(
            model_name='accountdata',
            name='password',
            field=models.CharField(default='', max_length=15, verbose_name='Password'),
        ),
    ]
