# Generated by Django 5.0 on 2024-01-06 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0011_alter_casino_affiliate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonusamount',
            options={'ordering': ['id'], 'verbose_name': 'Bonus Amount', 'verbose_name_plural': 'Bonus Amount'},
        ),
        migrations.AlterModelOptions(
            name='bonusmaxwin',
            options={'ordering': ['id'], 'verbose_name': 'Bonus MaxWin', 'verbose_name_plural': 'Bonus MaxWin'},
        ),
        migrations.AlterModelOptions(
            name='bonusmindep',
            options={'ordering': ['id'], 'verbose_name': 'Bonus Min Deposit', 'verbose_name_plural': 'Bonus Min Deposit'},
        ),
        migrations.AlterModelOptions(
            name='wageringcontribution',
            options={'ordering': ['id'], 'verbose_name': 'Wagering Contribution', 'verbose_name_plural': 'Wagering Contribution'},
        ),
        migrations.AddField(
            model_name='bonusmaxwin',
            name='unlimited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bonusmaxwin',
            name='max_value',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bonus Max Win value'),
        ),
        migrations.AlterField(
            model_name='bonusmaxwin',
            name='symbol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonus_max_win', to='app_casinos.basecurrency'),
        ),
    ]
