# Generated by Django 5.0 on 2023-12-31 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0011_alter_bonustype_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basecurrency',
            options={'ordering': ['id'], 'verbose_name': 'Base Currency', 'verbose_name_plural': 'Base Currencies'},
        ),
        migrations.CreateModel(
            name='BonusValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(null=True, verbose_name='Value %')),
                ('selected_source', models.CharField(choices=[('undefined', 'Undefined'), ('terms_and_conditions', 'Terms & Conditions'), ('support', 'Support'), ('website', 'Website')], default='', max_length=20)),
                ('bonus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonus_value', to='app_casinos.bonus', to_field='slug', unique=True)),
            ],
        ),
    ]
