# Generated by Django 5.0 on 2023-12-23 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0012_alter_accountdata_log_alter_accountdata_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdata',
            name='log',
            field=models.CharField(max_length=50, unique=True, verbose_name='Login'),
        ),
    ]
