# Generated by Django 5.0 on 2023-12-31 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0012_alter_basecurrency_options_bonusvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusMinDep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.IntegerField(null=True, verbose_name='Bonus min dep value')),
                ('selected_source', models.CharField(choices=[('undefined', 'Undefined'), ('terms_and_conditions', 'Terms & Conditions'), ('support', 'Support'), ('website', 'Website')], default='', max_length=20)),
                ('bonus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonus_min_dep', to='app_casinos.bonus', to_field='slug')),
                ('symbol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonus_min_dep', to='app_casinos.basecurrency')),
            ],
        ),
    ]
