# Generated by Django 5.0 on 2023-12-23 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0013_alter_accountdata_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdata',
            name='signature',
            field=models.CharField(choices=[('signed', 'Signature')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='accountdata',
            name='password',
            field=models.CharField(max_length=15, verbose_name='Password'),
        ),
    ]
