# Generated by Django 5.0 on 2023-12-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0013_alter_accountdata_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='casino',
            name='lick_loyalty',
            field=models.URLField(blank=True, help_text='URL of this casino on Casinoguru. For example - https://casinoguru-en.com/vavada-casino-review', null=True, verbose_name='URL Loyalty'),
        ),
    ]
