# Generated by Django 5.0 on 2024-01-08 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0013_bonussubtype_alter_casino_live_chat_competence_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonus',
            name='social_bonuses',
        ),
        migrations.CreateModel(
            name='SocialBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_bonuses', models.BooleanField(default=False)),
                ('selected_source', models.CharField(choices=[('undefined', 'Undefined'), ('terms_and_conditions', 'Terms & Conditions'), ('support', 'Support'), ('website', 'Website')], default='', max_length=20)),
                ('bonus', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_bonuses', to='app_casinos.bonus', to_field='slug')),
            ],
            options={
                'verbose_name': 'Social Bonus',
                'verbose_name_plural': 'Social Bonus',
                'ordering': ['id'],
            },
        ),
    ]
