# Generated by Django 5.0 on 2023-12-20 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0014_casino_lick_loyalty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casino',
            old_name='lick_loyalty',
            new_name='link_loyalty',
        ),
    ]
