# Generated by Django 5.0 on 2024-01-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0014_remove_bonus_social_bonuses_socialbonus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialbonus',
            name='social_bonuses',
        ),
        migrations.AddField(
            model_name='socialbonus',
            name='choice',
            field=models.BooleanField(default=False, verbose_name='social bonuses choice'),
        ),
        migrations.AlterField(
            model_name='bonusbuyfeature',
            name='choice',
            field=models.BooleanField(default=False, verbose_name='bonus buy feature choice'),
        ),
    ]
