# Generated by Django 5.0 on 2023-12-31 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0014_bonusexpiration'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('bonus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_period', to='app_casinos.bonus', to_field='slug', unique=True)),
            ],
        ),
    ]
