# Generated by Django 5.0 on 2023-12-23 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0014_accountdata_signature_alter_accountdata_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdata',
            name='signature',
            field=models.CharField(choices=[('not_signed', 'Not Signed'), ('signed', 'Signed')], default='', max_length=20),
        ),
    ]
