# Generated by Django 5.0 on 2023-12-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0015_rename_lick_loyalty_casino_link_loyalty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casino',
            name='link_loyalty',
            field=models.URLField(blank=True, null=True, verbose_name='URL Loyalty'),
        ),
    ]
