# Generated by Django 5.0 on 2023-12-31 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0015_promotionperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='social_bonuses',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='promotionperiod',
            name='selected_source',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('terms_and_conditions', 'Terms & Conditions'), ('support', 'Support'), ('website', 'Website')], default='', max_length=20),
        ),
        migrations.CreateModel(
            name='BonusMaxWin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_value', models.IntegerField(null=True, verbose_name='Bonus Max Win value')),
                ('selected_source', models.CharField(choices=[('undefined', 'Undefined'), ('terms_and_conditions', 'Terms & Conditions'), ('support', 'Support'), ('website', 'Website')], default='', max_length=20)),
                ('bonus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonus_max_win', to='app_casinos.bonus', to_field='slug')),
                ('symbol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonus_max_win', to='app_casinos.basecurrency')),
            ],
        ),
        migrations.CreateModel(
            name='Sticky',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sticky_value', models.BooleanField(default=False)),
                ('selected_source', models.CharField(choices=[('undefined', 'Undefined'), ('terms_and_conditions', 'Terms & Conditions'), ('support', 'Support'), ('website', 'Website')], default='', max_length=20)),
                ('bonus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sticky', to='app_casinos.bonus', to_field='slug', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TurnoverBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turnover_value', models.BooleanField(default=False)),
                ('selected_source', models.CharField(choices=[('undefined', 'Undefined'), ('terms_and_conditions', 'Terms & Conditions'), ('support', 'Support'), ('website', 'Website')], default='', max_length=20)),
                ('bonus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turnover_bonus', to='app_casinos.bonus', to_field='slug', unique=True)),
            ],
        ),
    ]
