# Generated by Django 5.0 on 2024-01-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0015_remove_socialbonus_social_bonuses_socialbonus_choice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turnoverbonus',
            name='turnover_value',
        ),
        migrations.AddField(
            model_name='turnoverbonus',
            name='choice',
            field=models.BooleanField(default=False, verbose_name='turnover bonus choice'),
        ),
    ]
