# Generated by Django 5.0 on 2024-01-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0016_remove_turnoverbonus_turnover_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='days_of_week',
            field=models.ManyToManyField(blank=True, choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], default=None, to='app_casinos.bonus'),
        ),
    ]
