# Generated by Django 5.0 on 2023-12-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0017_alter_minwagering_min_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='minwagering',
            name='unlimited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mindep',
            name='symbol',
            field=models.CharField(choices=[('$', 'USD'), ('RUB', 'EUR'), ('BNB', 'BNB')], max_length=3),
        ),
    ]
