# Generated by Django 5.0 on 2023-12-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0018_minwagering_unlimited_alter_mindep_symbol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minwagering',
            name='unlimited',
        ),
        migrations.AddField(
            model_name='withdrawallimit',
            name='unlimited',
            field=models.BooleanField(default=False),
        ),
    ]
