# Generated by Django 5.0 on 2024-01-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0018_dayofweek_alter_bonus_days_of_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='days_of_week',
            field=models.ManyToManyField(blank=True, to='app_casinos.dayofweek', verbose_name='Bonus activity days of the week'),
        ),
    ]
