# Generated by Django 5.0 on 2023-12-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0019_remove_minwagering_unlimited_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawallimit',
            name='daily',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='withdrawallimit',
            name='monthly',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='withdrawallimit',
            name='weekly',
            field=models.IntegerField(null=True),
        ),
    ]
