# Generated by Django 5.0 on 2024-01-08 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0020_alter_dayofweek_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dayofweek',
            options={'ordering': ['id']},
        ),
    ]
