# Generated by Django 5.0 on 2024-01-01 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0020_wager'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='bonus_only',
            field=models.IntegerField(null=True, verbose_name='Bonus Only'),
        ),
        migrations.AddField(
            model_name='bonus',
            name='bonus_plus_deposit',
            field=models.IntegerField(null=True, verbose_name='Bonus + Deposit'),
        ),
        migrations.AddField(
            model_name='bonus',
            name='bonus_plus_freespins_value',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bonus + Freespins value'),
        ),
    ]
