# Generated by Django 5.0 on 2024-01-08 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0021_alter_dayofweek_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasinoTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Casino Name')),
            ],
        ),
        migrations.AddField(
            model_name='casino',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casino', to='app_casinos.casinotheme', verbose_name='Casino Theme'),
        ),
    ]
