# Generated by Django 5.0 on 2024-01-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0022_casinotheme_casino_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casinotheme',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Description'),
        ),
    ]
