# Generated by Django 5.0 on 2024-01-01 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0022_wagering'),
    ]

    operations = [
        migrations.CreateModel(
            name='WageringContributionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default=None, max_length=255, verbose_name='Bonus Name')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WageringContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(null=True, verbose_name='Wagering Contribution value %')),
                ('selected_source', models.CharField(choices=[('undefined', 'Undefined'), ('terms_and_conditions', 'Terms & Conditions'), ('support', 'Support'), ('website', 'Website')], default='', max_length=20)),
                ('bonus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wagering_contribution', to='app_casinos.bonus', to_field='slug')),
                ('contribution_description', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wagering_contribution', to='app_casinos.wageringcontributionvalue')),
            ],
        ),
    ]
