# Generated by Django 5.0 on 2024-01-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0023_alter_casinotheme_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonusmaxwin',
            options={'ordering': ['id'], 'verbose_name': 'Bonus Max Win', 'verbose_name_plural': 'Bonus Max Win'},
        ),
        migrations.AlterModelOptions(
            name='sticky',
            options={'verbose_name': 'Sticky Or Not Sticky', 'verbose_name_plural': 'Sticky Or Not Sticky'},
        ),
        migrations.RemoveField(
            model_name='bonus',
            name='bonus_subtypes',
        ),
        migrations.AddField(
            model_name='bonus',
            name='bonus_subtype',
            field=models.ManyToManyField(blank=True, related_name='bonus', to='app_casinos.bonussubtype', verbose_name='Bonus Subtype'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='days_of_week',
            field=models.ManyToManyField(blank=True, to='app_casinos.dayofweek', verbose_name='Daily Availability'),
        ),
    ]
