# Generated by Django 5.0 on 2024-01-01 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0023_wageringcontributionvalue_wageringcontribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wageringcontributionvalue',
            name='description',
            field=models.CharField(default=None, max_length=255, verbose_name=' Wagering Contribution Description'),
        ),
        migrations.CreateModel(
            name='BonusRestrictionCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_source', models.CharField(choices=[('undefined', 'Undefined'), ('terms_and_conditions', 'Terms & Conditions'), ('support', 'Support'), ('website', 'Website')], default='', max_length=20)),
                ('bonus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restriction_country', to='app_casinos.bonus', to_field='slug', unique=True)),
                ('country', models.ManyToManyField(related_name='bonus_restriction_country', to='app_casinos.country')),
            ],
        ),
        migrations.CreateModel(
            name='BonusRestrictionGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_source', models.CharField(choices=[('undefined', 'Undefined'), ('terms_and_conditions', 'Terms & Conditions'), ('support', 'Support'), ('website', 'Website')], default='', max_length=20)),
                ('bonus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restriction_game', to='app_casinos.bonus', to_field='slug', unique=True)),
                ('game', models.ManyToManyField(related_name='bonus_restriction_game', to='app_casinos.game')),
            ],
        ),
        migrations.CreateModel(
            name='BonusRestrictionRtpGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(null=True, verbose_name='Games with RTP higher than %')),
                ('selected_source', models.CharField(choices=[('undefined', 'Undefined'), ('terms_and_conditions', 'Terms & Conditions'), ('support', 'Support'), ('website', 'Website')], default='', max_length=20)),
                ('bonus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restriction_rtp_game', to='app_casinos.bonus', to_field='slug', unique=True)),
            ],
        ),
    ]
