# Generated by Django 5.0 on 2024-01-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0024_alter_bonusmaxwin_options_alter_sticky_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonus',
            name='days_of_week',
        ),
        migrations.AddField(
            model_name='bonus',
            name='days',
            field=models.ManyToManyField(blank=True, null=True, to='app_casinos.dayofweek'),
        ),
    ]
