# Generated by Django 5.0 on 2024-01-08 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0025_remove_bonus_days_of_week_bonus_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(default=None, max_length=10, unique=True, verbose_name='Day')),
            ],
        ),
        migrations.RemoveField(
            model_name='bonus',
            name='days',
        ),
        migrations.RemoveField(
            model_name='dayofweek',
            name='day',
        ),
        migrations.AddField(
            model_name='dayofweek',
            name='bonus',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day_of_week', to='app_casinos.bonus', to_field='slug'),
        ),
        migrations.AddField(
            model_name='dayofweek',
            name='selected_source',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('terms_and_conditions', 'Terms & Conditions'), ('support', 'Support'), ('website', 'Website')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='dayofweek',
            name='days',
            field=models.ManyToManyField(blank=True, null=True, related_name='day_of_week', to='app_casinos.day'),
        ),
    ]
