# Generated by Django 5.0 on 2024-01-01 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0025_bonusmaxbet_bonusmaxbetautomatic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wageringcontributionvalue',
            name='description',
            field=models.CharField(default=None, max_length=255, verbose_name='Wagering Contribution Description'),
        ),
        migrations.CreateModel(
            name='BonusBuyFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.BooleanField(default=False)),
                ('selected_source', models.CharField(choices=[('undefined', 'Undefined'), ('terms_and_conditions', 'Terms & Conditions'), ('support', 'Support'), ('website', 'Website')], default='', max_length=20)),
                ('bonus', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buy_feature', to='app_casinos.bonus', to_field='slug')),
            ],
        ),
        migrations.CreateModel(
            name='BonusSpecialNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Special Note')),
                ('bonus', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='special_note', to='app_casinos.bonus', to_field='slug')),
            ],
        ),
    ]
