# Generated by Django 5.0 on 2024-01-17 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0027_alter_dayofweek_options_alter_bonus_bonus_only_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashbackPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Cashback Period')),
            ],
        ),
        migrations.CreateModel(
            name='CashbackType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Cashback Type')),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Loyalty Url')),
                ('loyalty_understandable', models.TextField(blank=True, null=True, verbose_name='Is this loyalty easy to understand')),
                ('level', models.CharField(blank=True, max_length=30, null=True, verbose_name='Level')),
                ('casino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_program', to='app_casinos.casino', to_field='slug')),
            ],
        ),
        migrations.CreateModel(
            name='Cashback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField(blank=True, null=True, verbose_name='Percentage %')),
                ('wager', models.IntegerField(blank=True, null=True, verbose_name='Wager X')),
                ('cashback_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashback', to='app_casinos.cashbackperiod')),
                ('cashback_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashback', to='app_casinos.cashbacktype')),
                ('loyalty_program', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cashback', to='app_casinos.loyaltyprogram')),
            ],
        ),
        migrations.CreateModel(
            name='PointAccumulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField(blank=True, null=True, verbose_name='Point')),
                ('value', models.IntegerField(blank=True, null=True, verbose_name='Value Point')),
                ('next_lvl', models.IntegerField(blank=True, null=True, verbose_name='Next Level')),
                ('level_value', models.IntegerField(blank=True, null=True, verbose_name='Level Value')),
                ('loyalty_program', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='point_accumulation', to='app_casinos.loyaltyprogram')),
            ],
        ),
    ]
