# Generated by Django 5.0 on 2024-01-19 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0028_cashbackperiod_cashbacktype_loyaltyprogram_cashback_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loyaltyprogram',
            name='level',
        ),
        migrations.CreateModel(
            name='LevelLoyalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(blank=True, max_length=30, null=True, verbose_name='Level')),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level_loyalty', to='app_casinos.loyaltyprogram')),
            ],
        ),
        migrations.AlterField(
            model_name='cashback',
            name='loyalty_program',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cashback', to='app_casinos.levelloyalty'),
        ),
        migrations.AlterField(
            model_name='pointaccumulation',
            name='loyalty_program',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='point_accumulation', to='app_casinos.levelloyalty'),
        ),
        migrations.CreateModel(
            name='LevelUpBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bonus')),
                ('wager', models.IntegerField(blank=True, null=True, verbose_name='Wager')),
                ('freespins', models.IntegerField(blank=True, null=True, verbose_name='Freespins')),
                ('loyalty_program', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level_up_bonus', to='app_casinos.levelloyalty')),
            ],
        ),
    ]
