# Generated by Django 5.0 on 2024-01-19 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0029_remove_loyaltyprogram_level_levelloyalty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loyaltyprogram',
            name='casino',
        ),
        migrations.AddField(
            model_name='casino',
            name='loyalty_program',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casino', to='app_casinos.loyaltyprogram'),
        ),
    ]
