# Generated by Django 5.0 on 2023-12-20 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0030_alter_withdrawallimit_casino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawallimit',
            name='casino',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_limit', to='app_casinos.casino'),
        ),
    ]
