# Generated by Django 5.0 on 2024-01-19 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0030_remove_loyaltyprogram_casino_casino_loyalty_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casino',
            name='loyalty_program',
        ),
        migrations.AddField(
            model_name='loyaltyprogram',
            name='casino',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_program', to='app_casinos.casino'),
        ),
    ]
