# Generated by Django 5.0 on 2024-01-19 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0031_remove_casino_loyalty_program_loyaltyprogram_casino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltyprogram',
            name='casino',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_program', to='app_casinos.casino'),
        ),
    ]
