# Generated by Django 5.0 on 2023-12-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0031_alter_withdrawallimit_casino'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='name3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Country Name-3'),
        ),
    ]
