# Generated by Django 5.0 on 2024-01-19 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0032_alter_loyaltyprogram_casino'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashback',
            old_name='loyalty_program',
            new_name='level_loyalty',
        ),
        migrations.RenameField(
            model_name='levelupbonus',
            old_name='loyalty_program',
            new_name='level_loyalty',
        ),
        migrations.RenameField(
            model_name='pointaccumulation',
            old_name='loyalty_program',
            new_name='level_loyalty',
        ),
        migrations.AddField(
            model_name='levelloyalty',
            name='special_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Special Notes'),
        ),
        migrations.AddField(
            model_name='levelloyalty',
            name='vip_manager_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loyaltyprogram',
            name='vip_manager',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='', max_length=3),
        ),
        migrations.CreateModel(
            name='Gifts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday', models.CharField(blank=True, max_length=100, null=True)),
                ('birthday', models.CharField(blank=True, max_length=100, null=True)),
                ('offline', models.CharField(blank=True, max_length=100, null=True)),
                ('personalized', models.CharField(blank=True, max_length=100, null=True)),
                ('exclusive', models.CharField(blank=True, max_length=100, null=True)),
                ('level_loyalty', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gifts', to='app_casinos.levelloyalty')),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_money', models.CharField(blank=True, max_length=100, null=True)),
                ('customized', models.CharField(blank=True, max_length=100, null=True)),
                ('weekly', models.CharField(blank=True, max_length=100, null=True)),
                ('monthly', models.CharField(blank=True, max_length=100, null=True)),
                ('level_loyalty', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_Bonus', to='app_casinos.levelloyalty')),
            ],
            options={
                'verbose_name': 'Bonuses',
                'verbose_name_plural': 'Bonuses',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SpecialPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freespins', models.IntegerField(blank=True, null=True)),
                ('free_bet', models.CharField(blank=True, max_length=100, null=True)),
                ('other', models.CharField(blank=True, max_length=100, null=True)),
                ('level_loyalty', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='special_prize', to='app_casinos.levelloyalty')),
            ],
        ),
        migrations.CreateModel(
            name='Withdrawals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faster_withdrawal', models.CharField(blank=True, max_length=50, null=True)),
                ('withdrawal_limits', models.CharField(blank=True, max_length=50, null=True)),
                ('level_loyalty', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='app_casinos.levelloyalty')),
            ],
        ),
    ]
