# Generated by Django 5.0 on 2024-01-20 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0034_alter_loyaltyprogram_vip_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltyprogram',
            name='vip_manager',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('yes', 'Yes'), ('no', 'No')], default='', max_length=10),
        ),
    ]
