# Generated by Django 5.0 on 2024-01-23 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0035_alter_loyaltyprogram_vip_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='casino',
            name='deposit_limit',
            field=models.BooleanField(default=False, help_text='A predetermined maximum amount of money that a player can deposit into their gambling account within a specific timeframe (daily, weekly, or monthly)'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='cool_off',
            field=models.BooleanField(default=False, help_text="A temporary suspension of a player's account, preventing them from accessing the gambling platform for a shorter period than self-exclusion"),
        ),
        migrations.AlterField(
            model_name='casino',
            name='loss_limit',
            field=models.BooleanField(default=False, help_text='A set limit on the total losses a player can incur during a specific time frame (daily, weekly, or monthly)'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='reality_check',
            field=models.BooleanField(default=False, help_text='Periodic notifications or alerts sent to players during their gambling session, reminding them of the time spent playing and the amounts wagered'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='self_assessment',
            field=models.BooleanField(default=False, help_text='Tools or questionnaires provided to players to assess their gambling behavior, habits, and potential risk of developing gambling-related problems'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='self_exclusion',
            field=models.BooleanField(default=False, help_text='A voluntary agreement by a player to exclude themselves from accessing the gambling platform for a specific duration, often ranging from a few months to several years'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='session_limit',
            field=models.BooleanField(default=False, help_text='A restriction on the amount of time a player can spend in a single gambling session'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='tournaments',
            field=models.BooleanField(default=False, help_text='If the casino has tournaments, please check the box', verbose_name='Tournaments'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='wager_limit',
            field=models.BooleanField(default=False, help_text='A predefined maximum amount of money that a player can wager (bet) within a specific period, typically daily, weekly, or monthly'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='withdrawal_lock',
            field=models.BooleanField(default=False, help_text='A feature that allows players to lock in their withdrawal requests, preventing them from canceling or reversing the withdrawal process'),
        ),
    ]
