# Generated by Django 5.0 on 2024-01-23 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0036_casino_deposit_limit_alter_casino_cool_off_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casino',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casino', to='app_casinos.casinotheme', verbose_name='Casino Theme'),
        ),
    ]
