# Generated by Django 5.0 on 2024-01-23 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0037_alter_casino_theme'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mindep',
            options={'ordering': ['id'], 'verbose_name': 'Min Deposit', 'verbose_name_plural': 'Min Deposit'},
        ),
        migrations.RenameField(
            model_name='casino',
            old_name='bonus_hunt_active_bonus',
            new_name='bonus_hunt_with_active_bonus',
        ),
    ]
