# Generated by Django 5.0 on 2024-01-23 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0038_alter_mindep_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casino',
            old_name='using_vpn',
            new_name='vpn_usage',
        ),
    ]
