# Generated by Django 5.0 on 2024-01-26 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0041_remove_sistercasino_casino_casino_sisters_casinos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casino',
            name='crypto_currencies',
            field=models.ManyToManyField(blank=True, null=True, related_name='casino', to='app_casinos.cryptocurrency'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='theme',
            field=models.ForeignKey(blank=True, help_text='Theme of the casino. Pick from the dropdown or add a new one', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casino', to='app_casinos.casinotheme', verbose_name='Casino Theme'),
        ),
    ]
