# Generated by Django 5.0 on 2023-12-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0042_alter_withdrawallimit_selected_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawallimit',
            name='selected_source',
            field=models.CharField(choices=[('terms_and_conditions', 'Terms & Conditions'), ('support', 'Support'), ('website', 'Website'), ('undefined', 'Undefined')], max_length=20),
        ),
        migrations.AlterField(
            model_name='withdrawallimit',
            name='unlimited',
            field=models.BooleanField(choices=[(False, 'Undefined'), (True, 'Defined')]),
        ),
    ]
