# Generated by Django 5.0 on 2024-01-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0042_alter_casino_crypto_currencies_alter_casino_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='casino',
            name='gamstop_self_exclusion',
            field=models.BooleanField(default=False, help_text='GAMSTOP will prevent from using gambling websites and apps run by companies licensed in Great Britain, for a period of players choosing', verbose_name='GAMSTOP self exclusion'),
        ),
    ]
