# Generated by Django 5.0 on 2024-01-26 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0043_casino_gamstop_self_exclusion'),
    ]

    operations = [
        migrations.AddField(
            model_name='casino',
            name='casino_rank',
            field=models.DecimalField(decimal_places=1, max_digits=10, null=True, verbose_name='Casino Rank'),
        ),
        migrations.AlterField(
            model_name='bonusamount',
            name='selected_source',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('terms_and_conditions', 'Terms & Conditions'), ('support', 'Support'), ('website', 'Website'), ('common_sense', 'Common Sense')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='bonusbuyfeature',
            name='selected_source',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('terms_and_conditions', 'Terms & Conditions'), ('support', 'Support'), ('website', 'Website'), ('common_sense', 'Common Sense')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='bonusexpiration',
            name='selected_source',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('terms_and_conditions', 'Terms & Conditions'), ('support', 'Support'), ('website', 'Website'), ('common_sense', 'Common Sense')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='bonusmaxbet',
            name='selected_source',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('terms_and_conditions', 'Terms & Conditions'), ('support', 'Support'), ('website', 'Website'), ('common_sense', 'Common Sense')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='bonusmaxbetautomatic',
            name='selected_source',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('terms_and_conditions', 'Terms & Conditions'), ('support', 'Support'), ('website', 'Website'), ('common_sense', 'Common Sense')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='bonusmaxwin',
            name='selected_source',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('terms_and_conditions', 'Terms & Conditions'), ('support', 'Support'), ('website', 'Website'), ('common_sense', 'Common Sense')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='bonusmindep',
            name='selected_source',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('terms_and_conditions', 'Terms & Conditions'), ('support', 'Support'), ('website', 'Website'), ('common_sense', 'Common Sense')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='bonusrestrictioncountry',
            name='selected_source',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('terms_and_conditions', 'Terms & Conditions'), ('support', 'Support'), ('website', 'Website'), ('common_sense', 'Common Sense')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='bonusrestrictiongame',
            name='selected_source',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('terms_and_conditions', 'Terms & Conditions'), ('support', 'Support'), ('website', 'Website'), ('common_sense', 'Common Sense')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='bonusrestrictionrtpgame',
            name='selected_source',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('terms_and_conditions', 'Terms & Conditions'), ('support', 'Support'), ('website', 'Website'), ('common_sense', 'Common Sense')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='bonusslot',
            name='selected_source',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('terms_and_conditions', 'Terms & Conditions'), ('support', 'Support'), ('website', 'Website'), ('common_sense', 'Common Sense')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='bonusvalue',
            name='selected_source',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('terms_and_conditions', 'Terms & Conditions'), ('support', 'Support'), ('website', 'Website'), ('common_sense', 'Common Sense')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='casino',
            name='classic_currency',
            field=models.ManyToManyField(blank=True, null=True, related_name='casino', to='app_casinos.classiccurrency'),
        ),
        migrations.AlterField(
            model_name='casino',
            name='live_chat_competence',
            field=models.CharField(choices=[('no_chat', 'No Chat'), ("didn't_answer_to_questions", "Didn't Answer to Questions"), ('high_competence', 'High Competence'), ('above_average', 'Above Average'), ('average', 'Average'), ('below_average', 'Below Average'), ('incompetent', 'Incompetent')], default='High Competence', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dayofweek',
            name='selected_source',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('terms_and_conditions', 'Terms & Conditions'), ('support', 'Support'), ('website', 'Website'), ('common_sense', 'Common Sense')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='freespinamount',
            name='selected_source',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('terms_and_conditions', 'Terms & Conditions'), ('support', 'Support'), ('website', 'Website'), ('common_sense', 'Common Sense')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='mindep',
            name='selected_source',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('terms_and_conditions', 'Terms & Conditions'), ('support', 'Support'), ('website', 'Website'), ('common_sense', 'Common Sense')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='minwagering',
            name='selected_source',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('terms_and_conditions', 'Terms & Conditions'), ('support', 'Support'), ('website', 'Website'), ('common_sense', 'Common Sense')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='onespin',
            name='selected_source',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('terms_and_conditions', 'Terms & Conditions'), ('support', 'Support'), ('website', 'Website'), ('common_sense', 'Common Sense')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='promotionperiod',
            name='selected_source',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('terms_and_conditions', 'Terms & Conditions'), ('support', 'Support'), ('website', 'Website'), ('common_sense', 'Common Sense')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='sistercasino',
            name='selected_source',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('terms_and_conditions', 'Terms & Conditions'), ('support', 'Support'), ('website', 'Website'), ('common_sense', 'Common Sense')], max_length=20),
        ),
        migrations.AlterField(
            model_name='socialbonus',
            name='bonus',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_bonuses', to='app_casinos.casino', to_field='slug'),
        ),
        migrations.AlterField(
            model_name='socialbonus',
            name='selected_source',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('terms_and_conditions', 'Terms & Conditions'), ('support', 'Support'), ('website', 'Website'), ('common_sense', 'Common Sense')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='sticky',
            name='selected_source',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('terms_and_conditions', 'Terms & Conditions'), ('support', 'Support'), ('website', 'Website'), ('common_sense', 'Common Sense')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='turnoverbonus',
            name='selected_source',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('terms_and_conditions', 'Terms & Conditions'), ('support', 'Support'), ('website', 'Website'), ('common_sense', 'Common Sense')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='wager',
            name='selected_source',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('terms_and_conditions', 'Terms & Conditions'), ('support', 'Support'), ('website', 'Website'), ('common_sense', 'Common Sense')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='wagering',
            name='selected_source',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('terms_and_conditions', 'Terms & Conditions'), ('support', 'Support'), ('website', 'Website'), ('common_sense', 'Common Sense')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='wageringbonusplusdeposit',
            name='selected_source',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('terms_and_conditions', 'Terms & Conditions'), ('support', 'Support'), ('website', 'Website'), ('common_sense', 'Common Sense')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='wageringcontribution',
            name='selected_source',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('terms_and_conditions', 'Terms & Conditions'), ('support', 'Support'), ('website', 'Website'), ('common_sense', 'Common Sense')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='withdrawallimit',
            name='selected_source',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('terms_and_conditions', 'Terms & Conditions'), ('support', 'Support'), ('website', 'Website'), ('common_sense', 'Common Sense')], default='', max_length=20),
        ),
    ]
