# Generated by Django 5.0 on 2023-12-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0044_alter_mindep_selected_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawallimit',
            name='unlimited',
            field=models.BooleanField(choices=[(False, 'Undefined'), (True, 'Defined')], default=''),
        ),
    ]
