# Generated by Django 5.0 on 2023-12-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0046_alter_withdrawallimit_daily_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mindep',
            name='selected_source',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('terms_and_conditions', 'Terms & Conditions'), ('support', 'Support'), ('website', 'Website')], max_length=20),
        ),
        migrations.AlterField(
            model_name='minwagering',
            name='selected_source',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('terms_and_conditions', 'Terms & Conditions'), ('support', 'Support'), ('website', 'Website')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sistercasino',
            name='selected_source',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('terms_and_conditions', 'Terms & Conditions'), ('support', 'Support'), ('website', 'Website')], max_length=20),
        ),
        migrations.AlterField(
            model_name='withdrawallimit',
            name='selected_source',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('terms_and_conditions', 'Terms & Conditions'), ('support', 'Support'), ('website', 'Website')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='withdrawallimit',
            name='unlimited',
            field=models.BooleanField(),
        ),
    ]
