# Generated by Django 5.0 on 2023-12-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0047_alter_mindep_selected_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='minwagering',
            name='unlimited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='minwagering',
            name='min_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='minwagering',
            name='selected_source',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('terms_and_conditions', 'Terms & Conditions'), ('support', 'Support'), ('website', 'Website')], default='', max_length=20),
        ),
    ]
