# Generated by Django 5.0 on 2024-01-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0047_alter_mindep_min_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdata',
            name='user_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='User Name'),
        ),
    ]
