# Generated by Django 5.0 on 2024-01-27 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0048_accountdata_user_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gametype',
            options={'ordering': ['id'], 'verbose_name': 'Game Type', 'verbose_name_plural': 'Game Type'},
        ),
    ]
