# Generated by Django 5.0 on 2023-12-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0048_minwagering_unlimited_alter_minwagering_min_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mindep',
            name='symbol',
        ),
        migrations.AddField(
            model_name='mindep',
            name='symbol',
            field=models.ManyToManyField(related_name='min_dip_symbol', to='app_casinos.cryptocurrency'),
        ),
    ]
