# Generated by Django 5.0 on 2023-12-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0049_remove_mindep_symbol_mindep_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mindep',
            name='min_value',
            field=models.IntegerField(null=True),
        ),
    ]
