# Generated by Django 5.0 on 2024-01-28 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0049_alter_gametype_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='casino',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='app_casinos.casino', to_field='slug', verbose_name='Casino Name'),
        ),
    ]
