# Generated by Django 5.0 on 2023-12-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0050_alter_mindep_min_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mindep',
            name='selected_source',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('terms_and_conditions', 'Terms & Conditions'), ('support', 'Support'), ('website', 'Website')], default='', max_length=20),
        ),
    ]
