# Generated by Django 5.0 on 2024-01-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0050_alter_bonus_casino'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gametype',
            options={'ordering': [models.Case(models.When(name='betting', then=models.Value(0)), models.When(name='esports betting', then=models.Value(1)), default=models.Value(2), output_field=models.IntegerField()), 'name'], 'verbose_name': 'Game Type', 'verbose_name_plural': 'Game Type'},
        ),
    ]
