# Generated by Django 5.0 on 2023-12-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0051_alter_mindep_selected_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='casino',
            name='affiliate_program',
            field=models.CharField(blank=True, choices=[('test_1', 'Test1'), ('test_2', 'Test2'), ('test_3', 'Test3')], max_length=255, null=True, verbose_name='Affiliate Program'),
        ),
        migrations.AddField(
            model_name='casino',
            name='link_affiliate',
            field=models.URLField(blank=True, null=True, verbose_name='Affiliate Link'),
        ),
        migrations.AddField(
            model_name='casino',
            name='link_affiliate_program',
            field=models.URLField(blank=True, null=True, verbose_name='affiliate Program URL'),
        ),
    ]
