# Generated by Django 5.0 on 2024-01-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0051_alter_gametype_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gametype',
            options={'ordering': [models.Case(models.When(name='Betting', then=models.Value(0)), models.When(name='Esports betting', then=models.Value(1)), default=models.Value(2), output_field=models.IntegerField()), 'name'], 'verbose_name': 'Game Type', 'verbose_name_plural': 'Game Type'},
        ),
        migrations.AddField(
            model_name='mindep',
            name='unlimited',
            field=models.BooleanField(default=False),
        ),
    ]
