# Generated by Django 5.0 on 2024-04-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0053_alter_mindep_min_value_alter_mindep_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashback',
            name='percentage',
            field=models.FloatField(blank=True, null=True, verbose_name='Percentage %'),
        ),
    ]
