# Generated by Django 5.0 on 2024-04-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0054_alter_cashback_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonusamount',
            name='unlimited',
            field=models.BooleanField(default=False),
        ),
    ]
