# Generated by Django 5.0 on 2023-12-22 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0055_alter_casinoimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliatesProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='casino',
            name='affiliate_program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casino_affiliate_program', to='app_casinos.affiliatesprogram'),
        ),
    ]
