# Generated by Django 5.0 on 2024-04-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0056_alter_bonusamount_symbol_alter_bonusamount_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionperiod',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='promotionperiod',
            name='start_date',
            field=models.DateField(blank=True, help_text='If there is something specific like Christmas bonus, then we should add the period during which it is available', null=True, verbose_name='Start Date'),
        ),
    ]
