# Generated by Django 5.0 on 2024-04-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0058_alter_bonusrestrictioncountry_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='game_providers',
            field=models.ManyToManyField(related_name='bonus', to='app_casinos.provider'),
        ),
    ]
