# Generated by Django 5.0 on 2024-04-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0059_bonus_game_providers'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecurrency',
            name='name2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name2 Currency'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='game_providers',
            field=models.ManyToManyField(related_name='bonus', to='app_casinos.provider', verbose_name='Providers'),
        ),
    ]
