# Generated by Django 5.0 on 2024-04-19 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0060_basecurrency_name2_alter_bonus_game_providers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonusbuyfeature',
            name='choice',
            field=models.BooleanField(default=False, verbose_name='bonus buy feature choice'),
        ),
        migrations.AlterField(
            model_name='bonusmaxbet',
            name='value',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bonus Max Bet value'),
        ),
        migrations.AlterField(
            model_name='bonusmaxbetautomatic',
            name='automatic',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bonusrestrictioncountry',
            name='country',
            field=models.ManyToManyField(blank=True, null=True, related_name='bonus_restriction_country', to='app_casinos.country'),
        ),
        migrations.AlterField(
            model_name='bonusrestrictiongame',
            name='bonus',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restriction_game', to='app_casinos.bonus', to_field='slug'),
        ),
        migrations.AlterField(
            model_name='bonusrestrictiongame',
            name='game',
            field=models.ManyToManyField(related_name='bonus_restriction_game', to='app_casinos.game'),
        ),
        migrations.AlterField(
            model_name='bonusrestrictionrtpgame',
            name='value',
            field=models.FloatField(blank=True, null=True, verbose_name='Games with RTP higher than %'),
        ),
        migrations.AlterField(
            model_name='bonusslot',
            name='game',
            field=models.ManyToManyField(blank=True, related_name='bonus_game', to='app_casinos.game'),
        ),
        migrations.AlterField(
            model_name='bonusspecialnote',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Special Note'),
        ),
        migrations.AlterField(
            model_name='freespinamount',
            name='value',
            field=models.IntegerField(blank=True, null=True, verbose_name='Free Spins value'),
        ),
        migrations.AlterField(
            model_name='onespin',
            name='value',
            field=models.FloatField(blank=True, null=True, verbose_name='One Spin value'),
        ),
        migrations.AlterField(
            model_name='turnoverbonus',
            name='choice',
            field=models.BooleanField(default=False, verbose_name='turnover bonus choice'),
        ),
        migrations.AlterField(
            model_name='wager',
            name='value',
            field=models.IntegerField(blank=True, null=True, verbose_name='Wager value'),
        ),
        migrations.AlterField(
            model_name='wageringcontribution',
            name='contribution_description',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wagering_contribution', to='app_casinos.wageringcontributionvalue'),
        ),
    ]
