# Generated by Django 5.0 on 2024-04-19 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0061_alter_bonusbuyfeature_choice_alter_bonusmaxbet_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonusrestrictioncountry',
            name='bonus',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restriction_country', to='app_casinos.bonus', to_field='slug'),
        ),
    ]
