# Generated by Django 5.0 on 2024-05-01 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0062_alter_bonusrestrictioncountry_bonus'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataAutoFillBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('data', models.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name='bonusslot',
            name='game',
            field=models.ManyToManyField(blank=True, related_name='bonus_game', to='app_casinos.game', verbose_name='Game Slot'),
        ),
    ]
