# Generated by Django 5.0 on 2024-05-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0063_dataautofillbonus_alter_bonusslot_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataautofillbonus',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
