# Generated by Django 5.0 on 2024-05-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0064_alter_dataautofillbonus_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataautofillbonus',
            options={'ordering': ['id'], 'verbose_name': 'Bonus Data AutoFill', 'verbose_name_plural': 'Bonus Data AutoFill'},
        ),
        migrations.AlterField(
            model_name='casino',
            name='language_live_chat',
            field=models.ManyToManyField(blank=True, help_text='List of languages in livechat', null=True, related_name='casino_live_chat', to='app_casinos.language'),
        ),
    ]
