# Generated by Django 5.0 on 2024-05-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0066_alter_casino_live_chat_competence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casino',
            name='live_chat_competence',
            field=models.CharField(blank=True, choices=[('', ''), ('no_chat', 'No Chat'), ("didn't_answer_to_questions", "Didn't Answer to Questions"), ('high_competence', 'High Competence'), ('above_average', 'Above Average'), ('average', 'Average'), ('below_average', 'Below Average'), ('incompetent', 'Incompetent')], default='', max_length=50, null=True),
        ),
    ]
