# Generated by Django 5.0 on 2024-05-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0069_bonus_bonus_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltyprogram',
            name='loyalty_rank',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name='Loyalty Rank'),
        ),
    ]
