# Generated by Django 5.0 on 2024-05-19 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0071_slotswageringcontribution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sistercasino',
            name='selected_source',
        ),
    ]
