# Generated by Django 5.0 on 2024-05-19 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0072_remove_sistercasino_selected_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='slug',
        ),
    ]
