# Generated by Django 5.0 on 2024-05-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0073_remove_paymentmethod_slug_remove_provider_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='casino',
            name='is_pars_data',
            field=models.BooleanField(default=False),
        ),
    ]
