# Generated by Django 5.0 on 2024-05-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0074_casino_is_pars_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='game_providers',
            field=models.ManyToManyField(blank=True, related_name='bonus', to='app_casinos.provider', verbose_name='Providers'),
        ),
    ]
