# Generated by Django 5.0 on 2024-05-25 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_casinos', '0076_stateprogram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stateprogram',
            name='start_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
